const not = require('./not');
const compare = require('./compare');
const int = require('./int');
const object = require('./object');
const append = require('./append');
const push = require('./push');
const t2d = require('./t2d');
const or = require('./or');
const and = require('./and');
const abs_url = require('./abs_url');
const encodeURI = require('./encodeURI');
const decodeURI = require('./decodeURI');
const replace = require('./replace');
const replaceNL = require('./replaceNL');
const replaceSQ = require('./replaceSQ');
const numberSeparator = require('./numberSeparator');
const removeUrlLang = require('./removeUrlLang');
const trans = require('./trans');
const route = require('./route');
const persianToSlug = require('./persianToSlug');

module.exports = async (engine) => {
    await engine.registerFilter('not', not);
    await engine.registerFilter('compare', compare);
    await engine.registerFilter('int', int);
    await engine.registerFilter('object', object);
    await engine.registerFilter('append', append);
    await engine.registerFilter('push', push);
    await engine.registerFilter('t2d', t2d);
    await engine.registerFilter('or', or);
    await engine.registerFilter('and', and);
    await engine.registerFilter('abs_url', abs_url);
    await engine.registerFilter('encodeURI', encodeURI);
    await engine.registerFilter('decodeURI', decodeURI);
    await engine.registerFilter('replace', replace);
    await engine.registerFilter('replaceSQ', replaceSQ);
    await engine.registerFilter('replaceNL', replaceNL);
    await engine.registerFilter('numberSeparator', numberSeparator);
    await engine.registerFilter('removeUrlLang', removeUrlLang);
    await engine.registerFilter('trans', trans);
    await engine.registerFilter('route', route);
    await engine.registerFilter('persianToSlug', persianToSlug);
    return true;
}