module.exports = `

    type Mutation {
        addRate(input: CreateRateInput): RateResponse
    }

    type RateResponse {
        average_rate: Float
        user_rate: Float
    }

    input CreateRateInput {
        model_id: ID
        rate: Float
    }
`;


    