const log = require("./log");
const render = require('./render');
const inlineSwitch = require('./inlineSwitch');
const var_tag = require('./var');
const global = require('./global');
const trans = require('./trans');
const mergeObject = require('./mergeObject');
const route = require('./route');
const varRoute = require('./varRoute');
const redirect = require('./redirect');
const page404 = require('./page404');
const setCookie = require("./setCookie");
const addToQuery = require("./addToQuery");

const getCartProductCount = require("./getCartProductCount");
const getAllUserTickets = require("./CRUD/getAllUserTickets");
const getAllDeputations = require("./CRUD/getAllDeputations");
const getBlogs = require("./CRUD/getBlogs");
const getBrands = require("./CRUD/getBrands");
const getBrandBySlug = require("./CRUD/getBrandBySlug");
const getBlogBySlug = require("./CRUD/getBlogBySlug");
const getBlogComments = require("./CRUD/getBlogComments");
const getProducts = require("./CRUD/getProducts");
const getProductBySlug = require("./CRUD/getProductBySlug");
const getProductComments = require("./CRUD/getProductComments");
const getSliderByKey = require("./CRUD/getSliderByKey");
const getCategories = require("./CRUD/getCategories");
const getCategory = require("./CRUD/getCategory");
const getCategoryBySlug = require("./CRUD/getCategoryBySlug");
const getCurrentUser = require("./CRUD/getCurrentUser");
const getCartDetails = require("./CRUD/getCartDetails");
const getOrderHistory = require("./CRUD/getOrderHistory");
const getUserInternalMessages = require("./CRUD/getUserInternalMessages");
const getUserComments = require("./CRUD/getUserComments");
const getUserTutorials = require("./CRUD/getUserTutorials");
const getUserDefaultAddress = require("./CRUD/getUserDefaultAddress");
const getAllUserAddresses = require("./CRUD/getAllUserAddresses");
const getUserShippingMethods = require("./CRUD/getUserShippingMethods");
const getUserPaymentMethods = require("./CRUD/getUserPaymentMethods");
const getSettingByKey = require("./CRUD/getSettingByKey");
const getSettingByKeys = require("./CRUD/getSettingByKeys");
const getTag = require("./CRUD/getTag");

module.exports = async (engine) => {
    engine.registerTag('log', log);
    engine.registerTag('render', render);
    engine.registerTag('inlineSwitch', inlineSwitch);

    engine.registerTag('assign', var_tag);
    engine.registerTag('var', var_tag);
    engine.registerTag('let', var_tag);
    engine.registerTag('global', global);
    engine.registerTag('trans', trans);
    engine.registerTag('mergeObject', mergeObject);

    engine.registerTag('route', route);
    engine.registerTag('varRoute', varRoute);
    engine.registerTag('letRoute', varRoute);
    engine.registerTag('constRoute', varRoute);
    engine.registerTag('redirect', redirect);
    engine.registerTag('page404', page404);
    engine.registerTag('setCookie', setCookie);
    engine.registerTag('addToQuery', addToQuery);

    engine.registerTag('getCartProductCount', getCartProductCount);
    engine.registerTag('getAllUserTickets', getAllUserTickets);
    engine.registerTag('getAllDeputations', getAllDeputations);
    engine.registerTag('getBlogs', getBlogs);
    engine.registerTag('getBrands', getBrands);
    engine.registerTag('getBrandBySlug', getBrandBySlug);
    engine.registerTag('getBlogBySlug', getBlogBySlug);
    engine.registerTag('getBlogComments', getBlogComments);
    engine.registerTag('getProducts', getProducts);
    engine.registerTag('getProductBySlug', getProductBySlug);
    engine.registerTag('getProductComments', getProductComments);
    engine.registerTag('getSliderByKey', getSliderByKey);
    engine.registerTag('getCategories', getCategories);
    engine.registerTag('getCategory', getCategory);
    engine.registerTag('getCategoryBySlug', getCategoryBySlug);
    engine.registerTag('getCurrentUser', getCurrentUser);
    engine.registerTag('getCartDetails', getCartDetails);
    engine.registerTag('getOrderHistory', getOrderHistory);
    engine.registerTag('getUserInternalMessages', getUserInternalMessages);
    engine.registerTag('getUserComments', getUserComments);
    engine.registerTag('getUserTutorials', getUserTutorials);
    engine.registerTag('getUserDefaultAddress', getUserDefaultAddress);
    engine.registerTag('getAllUserAddresses', getAllUserAddresses);
    engine.registerTag('getUserPaymentMethods', getUserPaymentMethods);
    engine.registerTag('getUserShippingMethods', getUserShippingMethods);
    engine.registerTag('getSettingByKey', getSettingByKey);
    engine.registerTag('getSettingByKeys', getSettingByKeys);
    engine.registerTag('getTag', getTag);
    return true;
}