export default {
    "title":"Title",
    "createdAt":"Created at",
    "updatedAt": "Updated at",
    "filter": "Filter",
    "selected": "Selected",
    "full_name": "full name",
    "clear_label": "Clear",
    "cancel_label": "Cancel",
    "today_label": "Today",
    "menu":"Menu",
    "notifications":'Notifications',
    "profile":'Profile',
    'home':'Home',
    "setting": "Setting",
    "logout" : "Logout",
    "add":"Add",
    "delete":"Delete",
    "edit":"Edit",
    "apply":"Apply",
    "operation": "Operation",
    "description":"Description",
    "sort":"Sort",
    "branch_team":"Branch Team",
    "branch_team_exception":"Branch Team",
    "powered_by":"Powered By",
    "password":"Password",
    "username":"Username",
    "login":"Login",
    "loginToAccount":"Login to your account",
    "delete_all":"Delete All",
    "ascending":"Ascending",
    "descending":"Deacending",
    "without_sort":"Without Sort",
    "select_all":"Select All"



};