module.exports = `

    type Query {
        getBrands(filter: BrandFilter ,page: Int , limit: Int , sort: BrandSort): BrandData
        getBrandBySlug(slug: String, type: Int): Brand
    }

    type BrandData {
        data: [Brand]
        paginate: Paginate
    }

    type Brand {
        id: ID
        title: JSON # multi language
        title_web: String @multilang(field:"title")
        show_in_menu: Boolean
        description: JSON # multi language
        description_web: String @multilang(field:"description")
        media: MediaStructure
        seo_id: ID
        createdAt: String
        updatedAt: String

        products: [Product]
        seo: SEO
    }

    input BrandFilter {
        search_title: String
        show_in_menu: Boolean
    }

    enum BrandSortFields {
        createdAt
        updatedAt
    }

    input BrandSort {
        field: BrandSortFields
        operator: sortEnum 
    }

`;
