module.exports = `

    type Query {
        getCategories(filter: CategoryFilter ,page: Int, limit: Int, sort: CategorySort): CategoryData
        getAllCategories(filter:CategoryFilter, sort: CategorySort): [Category]
        getCategory(category_id: ID): Category
        getCategoryBySlug(slug: String, type: Int): Category
    }

    type CategoryData {
        data: [Category]
        paginate: Paginate
    }

    type  Category {
        id: ID
        title: JSON # multi language
        title_web: String @multilang(field:"title")
        active: Boolean
        show_in_menu: Boolean
        description: JSON # multi language
        description_web: String @multilang(field:"description")
        type: Int
        sort: Int
        parent_id:ID
        media: MediaStructure
        seo_id: ID

        parent: Category
        children: [Category]
        seo: SEO
        blogs: [Blog]
        products: [Product]

        createdAt: String
        updatedAt: String
    }

     input sortCategoryInput {
        id: ID!
        sort: Int
        parent_id: ID
    }

    input CategoryFilter {
        type: Int
        show_in_menu: Boolean
        parent_id: String
       
    }

    enum CategorySortFields {
        sort
        createdAt
        updatedAt
    }

    input CategorySort {
        field: CategorySortFields
        operator: sortEnum 

    }
`


    