module.exports = `
    type  User {
        id: ID
        name: String
        last_name: String
        full_name: String
        username: String
        email: String
        mobile: String
        
        access_name: String
        gender: Int
        media: MediaStructure

        createdAt: String
        updatedAt: String
    }

    type Author {
        id: ID
        name: String
        last_name: String
        full_name: String
        email: String

        access_name: String
        gender: Int
        media: MediaStructure
    }
`;