module.exports = [
    {
        "_id": "608822598dbfb62038e5148d",
        "__v": "0",
        "action": "/components/menu-items",
        "action_type": null,
        "createdAt": "28/5/2021 08:20:21.067",
        "description": "توضیحات ...",
        "field": null,
        "key": "components_menu_items_menu_item",
        "kind_status": "1",
        "name": "مدیریت کامپوننت ها",
        "parent_id": null,
        "sort": "1",
        "type": "1",
        "updatedAt": "28/5/2021 08:20:21.067"
    },
    {
        "_id": "608abdb2a56d7c04c01454cb",
        "__v": "0",
        "action": "/accesses",
        "action_type": null,
        "createdAt": "28/5/2021 08:20:21.523",
        "description": "توضیحات ...",
        "field": null,
        "key": "accesses_menu_item",
        "kind_status": "1",
        "name": "مدیریت دسترسی ها",
        "parent_id": null,
        "sort": "2",
        "type": "1",
        "updatedAt": "28/5/2021 08:20:21.523"
    },
    {
        "_id": "608ac57e6d1162311ca6f0de",
        "__v": "0",
        "action": "/menu-items",
        "action_type": null,
        "createdAt": "28/5/2021 08:20:21.762",
        "description": "توضیحات ...",
        "field": null,
        "key": "menu_items_menu_item",
        "kind_status": "1",
        "name": "مدیریت منواتم ها",
        "parent_id": null,
        "sort": "3",
        "type": "1",
        "updatedAt": "28/5/2021 08:20:21.762"
    },
    {
        "_id": "607df2c4accf750cc894a5a8",
        "__v": "0",
        "action": "/users",
        "action_type": null,
        "createdAt": "28/5/2021 08:20:19.75",
        "description": "توضیحات ...",
        "field": null,
        "key": "users_menu_item",
        "kind_status": "1",
        "name": "مدیریت کاربران",
        "parent_id": null,
        "sort": "1",
        "type": "1",
        "updatedAt": "28/5/2021 08:20:19.75"
    },

    ...require('./mainComponents/users'),
    ...require('./mainComponents/accesses'),
    ...require('./mainComponents/access_components'),
    ...require('./mainComponents/menu_items'),

    ...require('./otherComponents/addresses'),
    ...require('./otherComponents/brands'),
    ...require('./otherComponents/docs'),
    ...require('./otherComponents/orders'),
    ...require('./otherComponents/inquiries'),
    ...require('./otherComponents/products'),
    ...require('./otherComponents/reports'),
    ...require('./otherComponents/settings'),
    ...require('./otherComponents/sliders'),
    ...require('./otherComponents/tags'),
    ...require('./otherComponents/transactions'),
    ...require('./otherComponents/tickets'),
    ...require('./otherComponents/deputations'),
    ...require('./otherComponents/discount'),
    ...require('./otherComponents/attributes'),
    ...require('./otherComponents/calendar'),
    ...require('./otherComponents/comments'),
    ...require('./otherComponents/crm_internal_messages'),
    ...require('./otherComponents/crm_external_messages'),
    ...require('./otherComponents/crm_email'),
    ...require('./otherComponents/crm_sms'),
    ...require('./otherComponents/crm_popup'),
    ...require('./otherComponents/crm_push_notification'),
    ...require('./otherComponents/employment'),
    ...require('./otherComponents/payment_gateways'),
    ...require('./otherComponents/shipping_methods'),

    ...require('./otherComponents/categories/categories_blog'),
    ...require('./otherComponents/categories/categories_catalogue'),
    ...require('./otherComponents/categories/categories_event'),
    ...require('./otherComponents/categories/categories_page'),
    ...require('./otherComponents/categories/categories_product'),
    ...require('./otherComponents/categories/categories_device'),
    ...require('./otherComponents/categories/categories_project'),
    ...require('./otherComponents/categories/categories_service'),

    ...require('./otherComponents/blogs/blogs'),
    ...require('./otherComponents/blogs/catalogues'),
    ...require('./otherComponents/blogs/events'),
    ...require('./otherComponents/blogs/pages'),
    ...require('./otherComponents/blogs/projects'),
    ...require('./otherComponents/blogs/services'),
];