# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# systemctl restart app-server.service
# systemctl restart app-panel.service

name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: cd server
    - run: yarn install
    - run: cd ../panel
    - run: yarn install
    - run: yarn build
    - run: systemctl restart app-server.service
    - run: systemctl restart app-panel.service